
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
      POSTGRES_DB: crypto_dashboard
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build:
      context: ./CryptoDashboard.Api
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=crypto_dashboard;Username=crypto;Password=crypto
      - ConnectionStrings__RedisConnection=redis:6379
      - ConnectionStrings__MongoDBConnection=mongodb://mongo:27017
    ports:
      - "5000:80"
    depends_on:
      - postgres
      - redis
      - mongo

  pg_restore:
    image: postgres:13
    depends_on:
      - postgres
    volumes:
      - ./crypto_dashboard.backup:/docker-entrypoint-initdb.d/crypto_dashboard.backup
    entrypoint: [ "bash", "-c", "sleep 10 && psql -h postgres -U crypto -d crypto_dashboard -f /docker-entrypoint-initdb.d/crypto_dashboard.backup" ]
    environment:
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
      POSTGRES_DB: crypto_dashboard

volumes:
  postgres_data:
  mongo_data:
