version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: crypto_dashboard
      POSTGRES_USER: crypto
      POSTGRES_PASSWORD: crypto
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
